name: Continuous Deployment

on:
  push:
    branches: [ "main" ]
    
env:
  ECR_REPOSITORY: sign-up-registry

jobs:

  sign-up-terraform:
    name: 'Sign Up Registry ECR Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate on AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: cd ./infra/; terraform init

    - name: Terraform Plan
      run: cd ./infra/; terraform plan -input=false

    - name: Terraform Apply
      run: cd ./infra/; terraform apply -auto-approve -input=false
  
  create-and-publish-image:
    permissions: write-all
    needs: sign-up-terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Authenticate on AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: docker build -t $ECR_REPOSITORY ./src/SignUp/

      - name: Tag Docker Image
        run: docker tag $ECR_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Push Docker Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

