name: Terraform

on:
  workflow_dispatch:

jobs:

  sign-up-terraform:
    name: 'Creating Registry ECR'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate on AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: cd ./infra/; terraform init

    - name: Terraform Plan
      run: cd ./infra/; terraform plan -input=false

    - name: Terraform Apply
      run: cd ./infra/; terraform apply -auto-approve -input=false